### ISSUE TITLE
[Bug]: Exception on slash command execution with optional parameter

### ISSUE THREAD

**Issue by Ruttie2006** [Remora/Remora.Discord#319]
### Description

When an optional parameter is added to a slash command, and that slash command is executed without said paramater, an exception occurs.
![image](https://github.com/Remora/Remora.Discord/assets/80394237/d3c29ed9-5d1f-46c9-9755-a4354f597f5b)

### Steps to Reproduce

Code:
```cs
    internal static class Program
    {
        const ulong GUILD = 0uL;
        const string PREFIX = "?";
        const GatewayIntents INTENTS = GatewayIntents.MessageContents;

        static readonly CancellationTokenSource Cts = new();
        static async Task Main()
        {
            Console.CancelKeyPress += (s, e) =>
            {
                e.Cancel = true;
                Cts.Cancel();
            };

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .CreateLogger();

            var prov = new ServiceCollection()
                .AddDiscordGateway(x => File.ReadAllText("token.txt"))
                .Configure<DiscordGatewayClientOptions>(static x =>
                {
                    x.Intents |= INTENTS;
                })
                .AddInteractivity()
                .AddDiscordCommands(true)
                .Configure<CommandResponderOptions>(x =>
                {
                    x.Prefix = PREFIX;
                })
                .AddInteractionGroup<Commands>()
                .AddCommandTree()
                .WithCommandGroup<Commands>()
                .Finish()
                .AddSerilog(dispose: true)
                .BuildServiceProvider();

            var slashService = prov.GetRequiredService<SlashService>();
            var appRes = await slashService.UpdateSlashCommandsAsync(DiscordSnowflake.New(GUILD));
            if (!appRes.IsSuccess)
                throw new InvalidOperationException(appRes.Error.Message);

            var gateway = prov.GetRequiredService<DiscordGatewayClient>();
            var runRes = await gateway.RunAsync(Cts.Token);

            if (!runRes.IsSuccess)
                throw new InvalidOperationException(runRes.Error.Message);
        }
    }
    internal class Commands(IFeedbackService feedback) : InteractionGroup
    {
        [Command("command")]
        [RequireContext(ChannelContext.Guild)]
        [RequireDiscordPermission(DiscordPermission.ManageGuild)]
        public async Task<Result> Command(IPartialRole? role = null)
        {
            if (role == null)
                return (Result)await feedback.SendContextualInfoAsync($"Hello without role.");
            else
                return (Result)await feedback.SendContextualInfoAsync($"Hello with role: {role.Name.OrThrow(static () => new InvalidCastException("Empty value."))}.");
        }
    }
```
Replace constants with applicable values.

### Expected Behavior

Command should execute without the parameter being set.

### Current Behavior

The following exception is printed in the console, and the command is not executed:
```txt
[16:51:29 WRN] Error in gateway event responder: Enumeration has not started. Call MoveNext.
System.InvalidOperationException: Enumeration has not started. Call MoveNext.
   at System.GenericEmptyEnumerator`1.get_Current()
   at Remora.Commands.Trees.Nodes.CommandNode.TryBind(IReadOnlyDictionary`2 namedParameters, BoundCommandNode& boundCommandShape, TreeSearchOptions searchOptions)
   at Remora.Commands.Trees.CommandTree.<>c__DisplayClass6_0.<Search>b__0(CommandNode c)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Remora.Commands.Services.CommandService.TryPrepareCommandAsync(IReadOnlyList`1 commandPath, IReadOnlyDictionary`2 namedParameters, IServiceProvider services, TokenizerOptions tokenizerOptions, TreeSearchOptions searchOptions, String treeName, CancellationToken ct)
   at Remora.Discord.Commands.Responders.InteractionResponder.TryExecuteCommandAsync(InteractionContext operationContext, IReadOnlyList`1 commandPath, IReadOnlyDictionary`2 parameters, String treeName, CancellationToken ct)
   at Remora.Discord.Commands.Responders.InteractionResponder.RespondAsync(IInteractionCreate gatewayEvent, CancellationToken ct)
   at Remora.Discord.Gateway.Services.ResponderDispatchService.<>c__DisplayClass17_0`1.<<DispatchEventAsync>b__0>d.MoveNext()
```

### Library / Runtime Information

Used packages:
```xml
    <PackageReference Include="Remora.Discord" Version="2023.4.0" />
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
```
.NET version: 8.0
LangVersion: preview (12)

**Comment by VelvetToroyashi** [comment]
With some investigative help from Vamplay on Discord, it turns out this is due to a [breaking change](https://github.com/dotnet/runtime/commit/32f6c070dc02bdb932e69c043912866b8d6a5d07) in .NET 8. PR inbound.

**Comment by Ruttie2006** [comment]
Any updates on a possible fix?
I would like to use optional parameters, but because of this I can't really...

**Comment by Nihlus** [comment]
@VelvetToroyashi

**Comment by VelvetToroyashi** [comment]
Last I recall @DPlayer234 had implied they would fix it, but I can PR their changes if need be https://canary.discord.com/channels/789912892426027039/789913038920744960/1163523508924579880

**Comment by DPlayer234** [comment]
@VelvetToroyashi I didn't mean to imply I'd make a PR. Feel free to go ahead.

**Comment by Ruttie2006** [comment]
I don't mean to be pushy, but is there any update on this?
( @VelvetToroyashi )

**Comment by VelvetToroyashi** [comment]
Hi sorry, I've been caught up with various projects. I'd have to look through my branches to see if I've already fixed this, but otherwise 'no', I'm afraid.
